# Generated by Django 4.1.4 on 2022-12-28 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manga',
            options={'verbose_name': 'Манга', 'verbose_name_plural': 'Манга'},
        ),
    ]
