# Generated by Django 4.1.4 on 2022-12-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_alter_manga_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='Translated_name',
            field=models.CharField(default=models.CharField(max_length=256, verbose_name='Название манги'), max_length=256, verbose_name='Перевод названия'),
        ),
        migrations.AddField(
            model_name='manga',
            name='release_date',
            field=models.DateField(default=None, verbose_name='Дата выхода'),
        ),
    ]
